#!/bin/sh

# Get SSID from uboot environment - should be of format 3FWi-Fi_XXXX
# We use the XXXX in our SmartScope default SSID
SSID_SUFFIX=`strings /dev/mtd1|grep SSID1|cut -d '_' -f 2`

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-iface[0].ssid="SmartScope ${SSID_SUFFIX}"
uci commit wireless
wifi

exit 0
